{% set name = "spherical_functions" %}
{% set pypiname = "spherical-functions" %}
{% set version = "2020.6.5.10.11.45" %}
{% set sha256 = "88344c04e1d0fedbe6eba8e28a0c2613702ee1686abc4b91b004c5118bbccc44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: package_version={{ version }} python -m pip install --no-deps --ignore-installed .  # [not win]
  script: set "package_version={{ version }}" && python -m pip install --no-deps --ignore-installed .  # [win]

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.13
    - scipy
    - numba
    - quaternion
    - spinsfast

test:
  imports:
    - spherical_functions

about:
  home: http://github.com/moble/spherical_functions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python/numba implementation of Wigner D Matrices, spin-weighted spherical harmonics, and associated functions
  description: |
    Python/numba package for evaluating and transforming Wigner’s 𝔇 matrices, Wigner’s 3-j symbols,
    and spin-weighted (and scalar) spherical harmonics. These functions are evaluated directly in
    terms of quaternions, as well as in the more standard forms of spherical coordinates and Euler
    angles.
  dev_url: https://github.com/moble/spherical_functions

extra:
  recipe-maintainers:
    - moble
