travis:
  secure:
    BINSTAR_TOKEN: O4/xJrImhMgneQHSp/LvswXl1lK0F5Iu0lu4jcwPWystUTDncqmr2eG/+o46T3SFA+4PmFlTSzkdgFNL7H7lbzalj1MP4fwLowz/axOfv7OM/LmsQNDyr/biAvPI0B9ita63f7xgcmCcT34vzy80sHiUENlpC3/zdeBW+l/aMniDQp3dHm81sNiE2pGs4WCJgZqRO18V3+3+2RVbhJviS9MsqlM6yybBfA1A7xfy0/iLr49HlO8CyBrvaMRc0leTQaGldAuT0v3nnv42tpeawbZqHu1uIfP+6CeqXlhrGPPgC2cXD3xuryKegoBW0b3SyLrzI+IcE5ViPoThNHxaDTfaG4tvQXqHqBQODsbXD9mzwlXWnPeZyYWfClZbX+b5GqYA6xM58JGcuhWTrvyYwiBEeeYiQWFwzv/HAgfr/i69fxnJDAKWnRBbzpVlluDDAqPgrNwpKYyNWDIEhbV6K7C49aj1RcwuoUiSf5VKpSXRmWL8msXnP+3EwX+58ZshD46PLQaCNng1ssaCmXtgh2x2vJ4mD9i7UWqY6YyMJZNUaXVQrzBqhdT/xX8zybyhFifJ05nTDBoL5snwgNhEwdUiQiaqLyHUKidswLosmaYfUlaBD2R6OdKRTbHoJt7shpX1eJd8JlkWb2qDDB2b1EPUJoJqp2VkVjW9mIexZBg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
